import { lazy, type ComponentType, type LazyExoticComponent } from 'react'
import {
  AppWindow,
  Binary,
  Braces,
  Camera,
  Clapperboard,
  Combine,
  Crop,
  Eraser,
  FileArchive,
  FileAudio,
  FileCode,
  FileImage,
  FileLock,
  FileSpreadsheet,
  FileText,
  FileType,
  FileVideo,
  Film,
  Gauge,
  ImageDown,
  Images,
  ListMusic,
  QrCode,
  ScanLine,
  LockOpen,
  Minimize2,
  Mic,
  MonitorPlay,
  MonitorUp,
  Palette,
  PenLine,
  Presentation,
  Scissors,
  Sheet,
  Signature,
  Stamp,
  type LucideIcon,
} from 'lucide-react'

export interface Tool {
  /** URL segment: the tool lives at #/<slug>. */
  slug: string
  title: string
  description: string
  icon: LucideIcon
  /** Accepted input → produced output, shown as chips on the card. */
  formats: string
  /** Optional short label on the card, e.g. "Baru". */
  badge?: string
  /** Which group the tool is listed under on the home page. */
  category: CategoryId
  /** Extra words people search with (file extensions, everyday terms). */
  keywords: string[]
  /** Lazy so each tool's libraries load only when that tool is opened. */
  component: LazyExoticComponent<ComponentType>
}

export type CategoryId = 'to-pdf' | 'from-pdf' | 'pdf' | 'media' | 'dev'

/** Home page groups, in display order. */
export const CATEGORIES: { id: CategoryId; title: string; description: string }[] = [
  { id: 'to-pdf', title: 'Ke PDF', description: 'Dokumen, presentasi, spreadsheet, dan gambar jadi PDF.' },
  {
    id: 'from-pdf',
    title: 'Dari PDF',
    description: 'Ambil isi PDF ke Word, Excel, PowerPoint, gambar, atau Markdown.',
  },
  {
    id: 'pdf',
    title: 'Olah & Amankan PDF',
    description: 'Gabung, pisah, beri watermark, tanda tangani, perkecil, kunci, dan buka kunci PDF.',
  },
  {
    id: 'media',
    title: 'Gambar & Media',
    description: 'Edit dan perkecil foto, video, dan audio: potong, ubah kecepatan, gabung, GIF, dan lainnya.',
  },
  {
    id: 'dev',
    title: 'Developer & Desain',
    description: 'QR code, favicon, Base64, warna, dan rapikan data.',
  },
]

// Adding a tool: create src/tools/<slug>/ with a default-exported component,
// then add one entry here (with its category). Nothing else needs to change.
export const TOOLS: Tool[] = [
  {
    slug: 'doc-to-pdf',
    category: 'to-pdf',
    keywords: ['word', 'docx', 'doc', 'dokumen', 'surat', 'cv', 'konversi'],
    title: 'Word ke PDF',
    description: 'Ubah dokumen Word (.docx) jadi PDF, langsung unduh.',
    icon: FileText,
    formats: 'DOCX → PDF',
    component: lazy(() => import('./doc-to-pdf/DocToPdf')),
  },
  {
    slug: 'pdf-to-word',
    category: 'from-pdf',
    keywords: ['word', 'docx', 'edit', 'ubah', 'dokumen', 'konversi'],
    title: 'PDF ke Word',
    description: 'Ambil teks dari PDF jadi dokumen Word (.docx) yang bisa diedit.',
    icon: FileType,
    formats: 'PDF → DOCX',
    component: lazy(() => import('./pdf-to-word/PdfToWord')),
  },
  {
    slug: 'image-to-pdf',
    category: 'to-pdf',
    keywords: ['foto', 'gambar', 'jpg', 'jpeg', 'png', 'webp', 'scan', 'gabung', 'konversi'],
    title: 'Gambar ke PDF',
    description: 'Gabungkan foto dan gambar jadi satu PDF — atur urutan, putar, dan pilih ukuran kertas.',
    icon: Images,
    formats: 'JPG / PNG → PDF',
    component: lazy(() => import('./image-to-pdf/ImageToPdf')),
  },
  {
    slug: 'ppt-to-pdf',
    category: 'to-pdf',
    keywords: ['powerpoint', 'pptx', 'ppt', 'presentasi', 'slide', 'konversi'],
    title: 'PowerPoint ke PDF',
    description: 'Ubah presentasi PowerPoint (.pptx) jadi PDF, satu halaman per slide.',
    icon: Presentation,
    formats: 'PPTX → PDF',
    component: lazy(() => import('./ppt-to-pdf/PptToPdf')),
  },
  {
    slug: 'excel-to-pdf',
    category: 'to-pdf',
    keywords: ['excel', 'xlsx', 'xls', 'csv', 'spreadsheet', 'tabel', 'laporan', 'konversi'],
    title: 'Excel ke PDF',
    description:
      'Ubah spreadsheet Excel (.xlsx) atau CSV jadi PDF tabel yang rapi, lengkap dengan warna dan format angka.',
    icon: FileSpreadsheet,
    formats: 'XLSX / CSV → PDF',
    component: lazy(() => import('./excel-to-pdf/ExcelToPdf')),
  },
  {
    slug: 'pdf-to-excel',
    category: 'from-pdf',
    keywords: ['excel', 'xlsx', 'spreadsheet', 'tabel', 'csv', 'data', 'konversi'],
    title: 'PDF ke Excel',
    description: 'Ambil tabel dari PDF jadi spreadsheet Excel (.xlsx) — angka langsung bisa dihitung.',
    icon: Sheet,
    formats: 'PDF → XLSX',
    component: lazy(() => import('./pdf-to-excel/PdfToExcel')),
  },
  {
    slug: 'pdf-to-ppt',
    category: 'from-pdf',
    keywords: ['powerpoint', 'pptx', 'presentasi', 'slide', 'konversi'],
    title: 'PDF ke PowerPoint',
    description: 'Ubah tiap halaman PDF jadi slide PowerPoint (.pptx) — teksnya tetap bisa diedit.',
    icon: MonitorPlay,
    formats: 'PDF → PPTX',
    component: lazy(() => import('./pdf-to-ppt/PdfToPpt')),
  },
  {
    slug: 'pdf-to-image',
    category: 'from-pdf',
    keywords: ['gambar', 'foto', 'png', 'jpg', 'jpeg', 'screenshot', 'konversi'],
    title: 'PDF ke Gambar',
    description: 'Simpan halaman PDF sebagai gambar PNG atau JPG, hingga 300 dpi.',
    icon: FileImage,
    formats: 'PDF → PNG / JPG',
    component: lazy(() => import('./pdf-to-image/PdfToImage')),
  },
  {
    slug: 'merge-pdf',
    category: 'pdf',
    keywords: ['gabung', 'satukan', 'merge', 'combine', 'jadikan satu', 'pdf'],
    title: 'Gabung PDF',
    description: 'Satukan beberapa PDF jadi satu file — atur urutannya dengan seret.',
    icon: Combine,
    formats: 'PDF + PDF → PDF',
    badge: 'Baru',
    component: lazy(() => import('./merge-pdf/MergePdf')),
  },
  {
    slug: 'split-pdf',
    category: 'pdf',
    keywords: ['pisah', 'pisahkan', 'potong', 'split', 'ekstrak', 'ambil halaman', 'halaman', 'rentang'],
    title: 'Pisah PDF',
    description: 'Ambil halaman tertentu, pisah per rentang, atau pecah tiap N halaman jadi PDF terpisah.',
    icon: Scissors,
    formats: 'PDF → PDF / ZIP',
    badge: 'Baru',
    component: lazy(() => import('./split-pdf/SplitPdf')),
  },
  {
    slug: 'watermark-pdf',
    category: 'pdf',
    keywords: ['watermark', 'tanda air', 'cap', 'stempel', 'logo', 'rahasia', 'draft', 'copy'],
    title: 'Watermark PDF',
    description: 'Pasang teks atau logo transparan di semua halaman — di tengah atau berulang.',
    icon: Stamp,
    formats: 'PDF → PDF + watermark',
    badge: 'Baru',
    component: lazy(() => import('./watermark-pdf/WatermarkPdf')),
  },
  {
    slug: 'sign-pdf',
    category: 'pdf',
    keywords: ['tanda tangan', 'ttd', 'paraf', 'sign', 'signature', 'tandatangan', 'kontrak', 'surat'],
    title: 'Tanda Tangan PDF',
    description: 'Gambar atau unggah tanda tanganmu, lalu tempel di halaman mana pun.',
    icon: Signature,
    formats: 'PDF → PDF + TTD',
    badge: 'Baru',
    component: lazy(() => import('./sign-pdf/SignPdf')),
  },
  {
    slug: 'compress-pdf',
    category: 'pdf',
    keywords: ['kompres', 'perkecil', 'kecilkan', 'ukuran', 'ringan', 'compress', 'optimasi'],
    title: 'Kompres PDF',
    description: 'Perkecil ukuran PDF dengan mengecilkan foto di dalamnya — teks tetap tajam.',
    icon: FileArchive,
    formats: 'PDF → PDF',
    component: lazy(() => import('./compress-pdf/CompressPdf')),
  },
  {
    slug: 'pdf-to-markdown',
    category: 'from-pdf',
    keywords: ['markdown', 'md', 'teks', 'text', 'notion', 'obsidian', 'konversi'],
    title: 'PDF ke Markdown',
    description: 'Ambil isi PDF jadi Markdown: judul, tebal/miring, daftar, dan tabel.',
    icon: FileCode,
    formats: 'PDF → MD',
    component: lazy(() => import('./pdf-to-markdown/PdfToMarkdown')),
  },
  {
    slug: 'protect-pdf',
    category: 'pdf',
    keywords: ['password', 'kunci', 'sandi', 'enkripsi', 'encrypt', 'aman', 'lock'],
    title: 'Proteksi PDF',
    description: 'Kunci PDF dengan password (AES-256) dan batasi cetak, salin, atau ubah.',
    icon: FileLock,
    formats: 'PDF → PDF + password',
    component: lazy(() => import('./protect-pdf/ProtectPdf')),
  },
  {
    slug: 'unlock-pdf',
    category: 'pdf',
    keywords: ['password', 'buka', 'sandi', 'dekripsi', 'decrypt', 'unlock', 'hapus password'],
    title: 'Buka Proteksi PDF',
    description: 'Hapus password atau batasan dari PDF milikmu.',
    icon: LockOpen,
    formats: 'PDF + password → PDF',
    component: lazy(() => import('./unlock-pdf/UnlockPdf')),
  },
  {
    slug: 'whiteboard',
    category: 'media',
    keywords: [
      'papan tulis',
      'whiteboard',
      'blackboard',
      'papan kapur',
      'coret',
      'corat-coret',
      'gambar',
      'menggambar',
      'sketsa',
      'paint',
      'catatan',
      'notes',
      'mengajar',
      'diagram',
      'stabilo',
    ],
    title: 'Papan Tulis',
    description: 'Whiteboard atau blackboard untuk menulis dan menggambar bebas — pena, stabilo, bentuk, teks, banyak halaman.',
    icon: PenLine,
    formats: 'Tulis tangan → PNG / PDF',
    badge: 'Baru',
    component: lazy(() => import('./whiteboard/Whiteboard')),
  },
  {
    slug: 'compress-video',
    category: 'media',
    keywords: ['video', 'mp4', 'mov', 'webm', 'kompres', 'perkecil', 'kecilkan', 'whatsapp', 'compress'],
    title: 'Kompres Video',
    description: 'Perkecil ukuran video dengan encoder bawaan perangkat — cepat, tanpa upload.',
    icon: FileVideo,
    formats: 'MP4 / MOV / WebM → MP4',
    badge: 'Baru',
    component: lazy(() => import('./compress-video/CompressVideo')),
  },
  {
    slug: 'crop-resize-image',
    category: 'media',
    keywords: ['crop', 'potong', 'resize', 'ubah ukuran', 'perkecil', 'putar', 'rotate', 'flip', 'balik', 'rasio', 'foto', 'gambar', 'jpg', 'png', 'webp', 'instagram'],
    title: 'Crop & Resize Gambar',
    description: 'Potong dengan rasio bebas atau 1:1, 16:9, 4:5; putar, balik, dan ubah ukuran piksel.',
    icon: Crop,
    formats: 'JPG / PNG / WebP → JPG / PNG / WebP',
    badge: 'Baru',
    component: lazy(() => import('./crop-resize-image/CropResizeImage')),
  },
  {
    slug: 'remove-background',
    category: 'media',
    keywords: ['hapus latar', 'hapus background', 'remove background', 'remove bg', 'transparan', 'png', 'pas foto', 'latar merah', 'latar biru', 'foto produk', 'magic wand', 'lasso'],
    title: 'Hapus Latar Gambar',
    description: 'Hapus latar dengan tongkat ajaib, pilih warna, lasso, atau kuas — lalu jadikan transparan atau ganti warna.',
    icon: Eraser,
    formats: 'JPG / PNG / WebP → PNG / JPG',
    badge: 'Baru',
    component: lazy(() => import('./remove-background/RemoveBackground')),
  },
  {
    slug: 'compress-image',
    category: 'media',
    keywords: [
      'foto',
      'gambar',
      'jpg',
      'jpeg',
      'png',
      'webp',
      'kompres',
      'perkecil',
      'kecilkan',
      'resize',
      'compress',
      'exif',
    ],
    title: 'Kompres Gambar',
    description: 'Perkecil foto dan gambar sekaligus banyak — JPG atau WebP, metadata GPS ikut dihapus.',
    icon: ImageDown,
    formats: 'JPG / PNG / WebP → JPG / WebP',
    badge: 'Baru',
    component: lazy(() => import('./compress-image/CompressImage')),
  },
  {
    slug: 'trim-media',
    category: 'media',
    keywords: ['potong', 'trim', 'cut', 'video', 'audio', 'mp3', 'mp4', 'lagu', 'klip', 'ringtone', 'nada dering', 'pendekkan'],
    title: 'Potong Video & Audio',
    description: 'Ambil bagian video atau lagu dengan menggeser penanda awal/akhir — format dan kualitas tetap.',
    icon: Clapperboard,
    formats: 'MP4 / MOV / WebM / MP3 / M4A / WAV',
    badge: 'Baru',
    component: lazy(() => import('./trim-media/TrimMedia')),
  },
  {
    slug: 'gif-mp4',
    category: 'media',
    keywords: ['gif', 'mp4', 'animasi', 'video', 'meme', 'konversi', 'whatsapp', 'stiker'],
    title: 'GIF ⇄ MP4',
    description: 'Ubah GIF jadi video MP4 yang jauh lebih kecil, atau potongan video jadi GIF.',
    icon: Film,
    formats: 'GIF ⇄ MP4',
    badge: 'Baru',
    component: lazy(() => import('./gif-mp4/GifMp4')),
  },
  {
    slug: 'extract-frames',
    category: 'media',
    keywords: ['frame', 'screenshot', 'tangkapan layar', 'thumbnail', 'gambar', 'foto', 'video', 'png', 'jpg', 'still'],
    title: 'Ekstrak Frame Video',
    description: 'Ambil frame video sebagai gambar resolusi asli — satu per satu atau otomatis tiap N detik.',
    icon: Camera,
    formats: 'Video → PNG / JPG / WebP',
    badge: 'Baru',
    component: lazy(() => import('./extract-frames/ExtractFrames')),
  },
  {
    slug: 'change-speed',
    category: 'media',
    keywords: ['kecepatan', 'speed', 'percepat', 'perlambat', 'slow motion', 'timelapse', 'video', 'audio', 'podcast', 'tempo'],
    title: 'Ubah Kecepatan',
    description: 'Percepat atau perlambat video dan audio (0,25×–4×) dengan nada suara tetap normal.',
    icon: Gauge,
    formats: 'Video → MP4 · Audio → MP3 / M4A / WAV',
    badge: 'Baru',
    component: lazy(() => import('./change-speed/ChangeSpeed')),
  },
  {
    slug: 'merge-audio',
    category: 'media',
    keywords: ['gabung', 'satukan', 'merge', 'join', 'audio', 'mp3', 'lagu', 'podcast', 'rekaman', 'medley'],
    title: 'Gabung Audio',
    description: 'Satukan beberapa file audio jadi satu — boleh beda format, atur urutan dan jeda.',
    icon: ListMusic,
    formats: 'Audio + Audio → MP3 / M4A / WAV',
    badge: 'Baru',
    component: lazy(() => import('./merge-audio/MergeAudio')),
  },
  {
    slug: 'screen-recorder',
    category: 'media',
    keywords: [
      'rekam layar',
      'screen recorder',
      'screen record',
      'perekam layar',
      'rekam tab',
      'rekam jendela',
      'tutorial',
      'presentasi',
      'loom',
      'kamera',
      'webcam',
      'video',
      'mp4',
    ],
    title: 'Rekam Layar',
    description: 'Rekam layar, jendela, atau tab — dengan suara mikrofon dan tab, plus kamera melayang. Unduh WebM atau MP4.',
    icon: MonitorUp,
    formats: 'Layar → WebM / MP4',
    badge: 'Baru',
    component: lazy(() => import('./screen-recorder/ScreenRecorder')),
  },
  {
    slug: 'audio-recorder',
    category: 'media',
    keywords: [
      'rekam',
      'rekam suara',
      'perekam',
      'recorder',
      'voice note',
      'voice recorder',
      'mikrofon',
      'mic',
      'rekaman',
      'rapat',
      'kuliah',
      'podcast',
      'mp3',
      'wav',
    ],
    title: 'Perekam Suara',
    description: 'Rekam suara dari mikrofon — jeda, lanjutkan, putar ulang, lalu unduh sebagai MP3, M4A, atau WAV.',
    icon: Mic,
    formats: 'Mikrofon → MP3 / M4A / WAV',
    badge: 'Baru',
    component: lazy(() => import('./audio-recorder/AudioRecorder')),
  },
  {
    slug: 'compress-audio',
    category: 'media',
    keywords: [
      'audio',
      'musik',
      'lagu',
      'mp3',
      'm4a',
      'aac',
      'opus',
      'ogg',
      'wav',
      'podcast',
      'suara',
      'kompres',
      'perkecil',
      'compress',
      'ekstrak',
    ],
    title: 'Kompres Audio',
    description: 'Perkecil file audio ke MP3, AAC, atau Opus — bisa juga mengambil suara dari video.',
    icon: FileAudio,
    formats: 'Audio / Video → MP3 / M4A / OGG',
    badge: 'Baru',
    component: lazy(() => import('./compress-audio/CompressAudio')),
  },
  {
    slug: 'qr-generator',
    category: 'dev',
    keywords: ['qr', 'qr code', 'kode qr', 'barcode', 'wifi', 'whatsapp', 'wa', 'kontak', 'vcard', 'link', 'tautan', 'menu', 'buat'],
    title: 'Generator QR Code',
    description: 'Buat QR code untuk tautan, teks, Wi-Fi, WhatsApp, kontak, atau email — bisa pakai logo dan warna.',
    icon: QrCode,
    formats: 'Teks → PNG / SVG',
    badge: 'Baru',
    component: lazy(() => import('./qr/QrGenerator')),
  },
  {
    slug: 'qr-reader',
    category: 'dev',
    keywords: ['qr', 'qr code', 'kode qr', 'barcode', 'kode batang', 'ean', 'scan', 'pindai', 'baca', 'kamera', 'scanner', 'reader', 'wifi'],
    title: 'Pembaca QR & Barcode',
    description: 'Pindai QR code atau barcode dari gambar, screenshot, atau kamera — isi Wi-Fi, kontak, dan tautan ditampilkan rapi.',
    icon: ScanLine,
    formats: 'Gambar / Kamera → Teks',
    badge: 'Baru',
    component: lazy(() => import('./qr/QrReader')),
  },
  {
    slug: 'json-beautify',
    category: 'dev',
    keywords: ['json', 'format', 'rapikan', 'pretty', 'beautify', 'indent', 'validasi', 'validator'],
    title: 'JSON Beautifier',
    description: 'Rapikan JSON dengan indentasi, urutkan key, dan temukan kesalahan sintaks beserta posisinya.',
    icon: Braces,
    formats: 'JSON → JSON rapi',
    badge: 'Baru',
    component: lazy(() => import('./json/JsonBeautify')),
  },
  {
    slug: 'json-minify',
    category: 'dev',
    keywords: ['json', 'minify', 'padatkan', 'kecilkan', 'compress'],
    title: 'JSON Minify',
    description: 'Padatkan JSON jadi satu baris tanpa spasi — angka dan teks tidak berubah sedikit pun.',
    icon: Minimize2,
    formats: 'JSON → JSON ringkas',
    badge: 'Baru',
    component: lazy(() => import('./json/JsonMinify')),
  },
  {
    slug: 'favicon-generator',
    category: 'dev',
    keywords: ['favicon', 'ico', 'icon', 'ikon', 'logo', 'website', 'apple touch', 'manifest', 'pwa', 'emoji'],
    title: 'Generator Favicon',
    description: 'Buat favicon.ico, ikon iOS & Android, dan web manifest dari logo, huruf, atau emoji.',
    icon: AppWindow,
    formats: 'PNG / SVG / teks → ICO + PNG',
    badge: 'Baru',
    component: lazy(() => import('./favicon-generator/FaviconGenerator')),
  },
  {
    slug: 'image-to-base64',
    category: 'dev',
    keywords: ['base64', 'data url', 'data uri', 'encode', 'decode', 'gambar', 'css', 'html', 'inline'],
    title: 'Gambar ⇄ Base64',
    description: 'Ubah gambar jadi Base64 / data URL siap tempel di HTML, CSS, atau Markdown — dan sebaliknya.',
    icon: Binary,
    formats: 'Gambar ⇄ Base64',
    badge: 'Baru',
    component: lazy(() => import('./image-to-base64/ImageToBase64')),
  },
  {
    slug: 'color-picker',
    category: 'dev',
    keywords: ['warna', 'color', 'colour', 'hex', 'rgb', 'hsl', 'oklch', 'cmyk', 'pipet', 'eyedropper', 'palet', 'palette', 'kontras', 'contrast', 'wcag'],
    title: 'Color Picker',
    description: 'Ambil warna dari gambar atau layar, ubah ke HEX/RGB/HSL/OKLCH, cek kontras, dan buat gradasi.',
    icon: Palette,
    formats: 'HEX / RGB / HSL / OKLCH',
    badge: 'Baru',
    component: lazy(() => import('./color-picker/ColorPicker')),
  },
]

export function findTool(slug: string) {
  return TOOLS.find((t) => t.slug === slug)
}
